### ISSUE TITLE
redmine2.3.x系でエラーになる

### ISSUE THREAD

**Issue by agilemasayuki** [agileware-jp/redmine_work_days#6]
redmine2.3系でガントチャートタブを表示しようとするとエラーになる。

Completed 500 Internal Server Error in 19ms

ActionView::Template::Error (undefined method `draw_relations' for #<IssueQuery:0x007fc4e1f4f5a8>):
    29:           <fieldset>
    30:             <legend><%= l(:label_related_issues) %></legend>
    31:             <label for="draw_relations">
    32:               <%= check_box 'query', 'draw_relations', :id => 'draw_relations' %>
    33:               <% rels = [IssueRelation::TYPE_BLOCKS, IssueRelation::TYPE_PRECEDES] %>
    34:               <% rels.each do |rel| %>
    35:                 <% color = Redmine::Helpers::Gantt::DRAW_TYPES[rel][:color] %>
  app/controllers/gantts_controller.rb:43:in`block (2 levels) in show'
  app/controllers/gantts_controller.rb:42:in `show'

**Comment by agilekawabata** [comment]
Redmine2.3.x系も本家サポート終了のためクローズとします。
